### ISSUE TITLE
No support for >20MHz processeors

### ISSUE THREAD

**Issue by ashishsk** [PaulStoffregen/SoftwareSerial#12]
I am using Feather M4 Express (ATSAMD51 controller on it) and I am unable to compile the code.
`lib/SoftwareSerial/SoftwareSerial.cpp:362:2: error: 
#error This version of SoftwareSerial supports only 20, 16 and 8MHz processors`

**Comment by PaulStoffregen** [comment]
You're asking in the wrong this.  This copy of SoftSerial is for Teensy only.  It's never used on any Adafruit boards.
