### ISSUE TITLE
error: Stream.h: No such file or directory

### ISSUE THREAD

**Issue by yassirnajmaoui** [PaulStoffregen/SoftwareSerial#6]
I am trying to compile the example given in the library ("SoftwareSerialExample.ino") and Arduino IDE gives me an error saying:
`
In file included from C:\Users\myusername\Downloads\SoftwareSerial-master\examples\SoftwareSerialExample\SoftwareSerialExample.ino:28:0:
SoftwareSerial.h:36:20: error: Stream.h: No such file or directory
 #include <Stream.h>
                    ^
compilation terminated.
`

Where can I find the library `Stream` ?

**Comment by PaulStoffregen** [comment]
Are you *really* using Arduino?

**Comment by yassirnajmaoui** [comment]
I am using Arduino IDE, but I was actually using stm32duino because I was trying to program in an STM32F303RE. I figured out my problem was with the Arduino Core library that was not exactly similar. I will try to use HardwareSerial instead. Thank you. You can close this issue now.

**Comment by amanem1** [comment]
hey ,i am facing problem of stream.h not found in atmel studio ........ how can i fix it ? and is there any specific c library by adding which i can get rid of all these problems ?

**Comment by PaulStoffregen** [comment]
Fix the problem by using Arduino IDE and a board which provides a compatible core library (almost all do).
