### ISSUE TITLE
SoftwareSerial on Platformio doesn't work for nRF51

### ISSUE THREAD

**Issue by damianb50** [PaulStoffregen/SoftwareSerial#9]
Hello there. Your library is available on platformio libraries and is signed as compatible with Nordic nRF51 platform. Apparently, it doesn't compile there 
https://platformio.org/lib/show/7212/SoftwareSerial

.pio\libdeps\waveshare_ble400\SoftwareSerial_ID7212\SoftwareSerial.cpp: In member function 'bool SoftwareSerial::listen()':
.pio\libdeps\waveshare_ble400\SoftwareSerial_ID7212\SoftwareSerial.cpp:341:23: error: 'SREG' was not declared in this scope
     uint8_t oldSREG = SREG;
                       ^~~~
.pio\libdeps\waveshare_ble400\SoftwareSerial_ID7212\SoftwareSerial.cpp:341:23: note: suggested alternative: 'SING'
     uint8_t oldSREG = SREG;
                       ^~~~
                       SING
.pio\libdeps\waveshare_ble400\SoftwareSerial_ID7212\SoftwareSerial.cpp:342:5: error: 'cli' was not declared in this scope
     cli();
     ^~~
In file included from .pio\libdeps\waveshare_ble400\SoftwareSerial_ID7212\SoftwareSerial.cpp:43:0:
.pio\libdeps\waveshare_ble400\SoftwareSerial_ID7212\SoftwareSerial.cpp: In member function 'void SoftwareSerial::setTX(uint8_t)':

C:\Users\xxxxxx\.platformio\packages\framework-arduinonordicnrf5\cores\nRF5/Arduino.h:95:38: error: invalid conversion from 'NRF_

GPIO_Type*' to 'uint8_t {aka unsigned char}' [-fpermissive]
 #define digitalPinToPort(P)        ( &(NRF_GPIO[P]) )
                                    ~~^~~~~~~~~~~~~~~~
.pio\libdeps\waveshare_ble400\SoftwareSerial_ID7212\SoftwareSerial.cpp:517:18: note: in expansion of macro 'digitalPinToPort'
   uint8_t port = digitalPinToPort(tx);
                  ^~~~~~~~~~~~~~~~
C:\Users\xxxxxx\.platformio\packages\framework-arduinonordicnrf5\cores\nRF5/Arduino.h:98:44: error: base operand of '->' is not a
 pointer
 #define portOutputRegister(port)   ( &(port->OUTSET) )
                                            ^
.pio\libdeps\waveshare_ble400\SoftwareSerial_ID7212\SoftwareSerial.cpp:518:27: note: in expansion of macro 'portOutputRegister'
   _transmitPortRegister = portOutputRegister(port);

**Comment by PaulStoffregen** [comment]
This is the wrong place to report problems with Nordic chips.

This copy of SoftwareSerial is for Teensy only.
